BATCH_SIZE = 10_000

DATA_DIR = "data"

PROCESSED_DIR = f"{DATA_DIR}/processed"
SOURCE_PATH = f"{DATA_DIR}/timeline.json"
ROAD_NETWORK_DIR = f"{DATA_DIR}/road_network"

JUMP_RATE = 0.05
MAX_JUMP_POINTS = 3

ROAD_NETWORK_CACHE_MARGIN = 5_000
ROAD_NETWORK_VIEW_MARGIN = 1_000
